message_center/urls.py
from django.conf.urls import url

from . import consumers, views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^conversation/(\d+)/', views.ConversationView.as_view(),
            name='conversation'),
]

wayup_challenge/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login, name="login"),
    url(r'^logout/$', logout, name="logout"),
    url(r'', include('message_center.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

message_center/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class MessageQuerySet(models.QuerySet):
    def between(self, user1, user2, order='ascending'):
        order_by = 'created_at' if order=='ascending' else '-created_at'
        q = Q(sender=user1, recipient=user2) | Q(sender=user2, recipient=user1)
        return self.filter(q).order_by(order_by)

    def sent_by(self, user):
        return self.filter(sender=user).order_by('-created_at')

    def sent_to(self, user):
        return self.filter(recipient=user).order_by('-created_at')


class MessageManager(models.Manager):
    def get_queryset(self):
        return MessageQuerySet(self.model, using=self._db)

    def between(self, user1, user2):
        return self.get_queryset().between(user1, user2)

    def sent_by(self, user):
        return self.get_queryset().sent_by(user)

    def sent_to(self, user):
        return self.get_queryset().sent_to(user)

    def create_from_form(self, request, form):
        new_msg = Message(
                sender=request.user, 
                recipient=User.objects.get(pk=form.data['recipient']),
                subject=form.data['subject'],
                body=form.data['body'],
        )
        new_msg.save()
        return new_msg

    def create_from_form_json(self, user, form_data):
        get_field = lambda s: [f for f in form_data if f['name']==s][0]
        new_msg = Message(
                sender=user,
                recipient=User.objects.get(
                        pk=get_field('recipient')['value']
                ),
                subject=get_field('subject')['value'],
                body=get_field('body')['value'],
        )
        new_msg.save()
        return new_msg


class Message(BaseModel):
    '''A message sent between two users'''
    DATE_FMT = '%m/%d/%y %H:%M:%S'
    SUBJECT_DEFAULT = "[no subject]"

    body = models.TextField(blank=False)
    recipient = models.ForeignKey(User, related_name='received_messages',
            blank=False, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='sent_messages', 
            blank=False, on_delete=models.CASCADE)
    subject = models.CharField(max_length=255, blank=True, 
            default=SUBJECT_DEFAULT)
    unread = models.BooleanField(default=True)

    messages = MessageManager()

    def __str__(self):
        return "%s to %s: %s (%s)" % (self.sender, self.recipient,
                self.subject, self.created_at.strftime(self.DATE_FMT))

    def to_json(self):
        user_to_dict = lambda u: {'id': u.id, 'name': u.username}
        # should really be part of User, but using default user
        return json.dumps({
                'id': self.id,
                'sender': user_to_dict(self.sender),
                'recipient': user_to_dict(self.recipient),
                'subject': self.subject,
                'body': self.body,
                'unread': self.unread,
                'created_at': self.created_at.strftime(self.DATE_FMT),
        })

message_center/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Message


def _get_user_choices():
    all_users = User.objects.all()
    return [(u.id, u.username) for u in all_users]


class BaseMessageForm(forms.Form):
    subject = forms.CharField(max_length=255, required=True,
            initial=Message.SUBJECT_DEFAULT)
    body = forms.CharField(required=True, widget=forms.Textarea)


class MessageForm(BaseMessageForm):
    '''A form for creating a new Message, sent by the current user,
    to the selected user.'''
    recipient = forms.ChoiceField(choices=_get_user_choices, 
            required=True)


class ReplyForm(BaseMessageForm):
    '''A form specifically for sending a Message from the conversations
    view'''
    pass

message_center/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json
import logging
import sys

from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views.generic.base import View

from .forms import MessageForm, ReplyForm
from .models import Message


class IndexView(LoginRequiredMixin, View):
    template_name = 'message_center/index.html'
    form_class = MessageForm

    def _get_shared_context(self, request):
        msgs = Message.messages.sent_to(request.user)
        sent_messages = Message.messages.sent_by(request.user)
        all_msgs_json = ([m.to_json() for m in msgs] 
                + [m.to_json() for m in sent_messages]
        )
        return {
                'my_messages': msgs,
                'sent_messages': sent_messages,
                'json_messages': all_msgs_json,
        }

    def get(self, request):
        msgs = Message.messages.sent_to(request.user)
        context = self._get_shared_context(request)
        context['form'] = self.form_class()
        context['sent_messages'] = Message.messages.sent_by(request.user)
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                Message.messages.create_from_form(request, form)
                # TODO flash success
                return redirect('index')
            except:
                err = sys.exc_info()[0]
                logging.error(err)
                # TODO flash error
        context = self._get_shared_context(request)
        context['form'] = form
        return render(request, self.template_name, context)


class ConversationView(LoginRequiredMixin, View):
    template_name = 'message_center/conversation.html'
    form_class = ReplyForm

    def _get_shared_context(self, request, user_id):
        other_user = User.objects.get(pk=user_id)
        return {
                'msgs': Message.messages.between(request.user, other_user),
                'other_user': other_user,
                'form': self.form_class(),
        }


    def get(self, request, user_id):
        other_user = User.objects.get(pk=user_id)
        context = self._get_shared_context(request, user_id)
        return render(request, self.template_name, context)

    def post(self, request, user_id):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                Message.messages.create(
                        sender=request.user,
                        recipient=User.objects.get(pk=user_id),
                        subject=form.data['subject'],
                        body=form.data['body'],
                )
                # TODO flash success
            except:
                err = sys.exc_info()[0]
                logging.error(err)
                # TODO flash error
        context = self._get_shared_context(request, user_id)
        context['form'] = form
        return render(request, self.template_name, context)

message_center/templates/message_center/_sidebar_item.html
<li>
    <a id="{{ forloop.counter0|add:offset }}" onclick="selectMessage(this.id)">"{{ message.subject }}" from {{ message.sender }}</a>
</li>

message_center/templates/message_center/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>
            {% block title %}{% endblock %}&nbsp;|&nbsp;Message Central
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="stylesheet" type="text/css" href="{% static 'foundation/css/foundation.min.css' %}">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="{% static 'foundation/css/app.css' %}">
        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% block header %}{% include "message_center/header.html" %}{% endblock %}

        <div class="grid-container full">
            {% block content %}{% endblock %}

            {% block footer %}{% include "message_center/footer.html" %}{% endblock %}
        </div>

        {# Global javascript #}
        <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="{% static 'foundation/js/vendor/what-input.js' %}"></script>
        <script type="text/javascript" src="{% static 'foundation/js/vendor/foundation.js' %}"></script>
        <script type="text/javascript" src="{% static 'foundation/js/app.js' %}"></script>
        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

message_center/templates/message_center/conversation.html
{% extends 'message_center/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<br/>
<div class="grid-x align-center">
    <div class="callout large primary">
        <div class="row column text-center">
            <h2>Messages between you and {{ other_user.username }}</h2>
            <p class="lead">(<a href="{% url 'index' %}">back home</a>)</p>
        </div>
    </div>
</div>

<div class="grid-x align-center" id="content">

    <div class="medium-1">
        &nbsp;
    </div>

    <div class="medium-8 cell">
        {% for msg in msgs %}
        <div class="card{% if msg.sender == user %} by-me{% endif %}">
            <div class="card-divider message-header">
                <p>From {{ msg.sender }} <small>at {{ msg.created_at|date:'H:i:s m/d/y' }}</small></p>
            </div>
            <div class="card-section message-details">
                <h4 class="message-subject">{{ msg.subject }}</h4>
                <p class="message-body">{{ msg.body }}</p>
            </div>
        </div>
        {% endfor %}
        <hr/>
        <div>
            <form method="post" action="{% url 'conversation' other_user.id %}" id="new-message-form">
                {% csrf_token %}
                {{ form }}
                <input type="submit" id="send-new-message" class="button button-small button-primary" value="Send reply!">
            </form>
        </div>
    </div>

    <div class="medium-1">
        &nbsp;
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'message_center/reconnecting-websocket.min.js' %}"></script>

<script>
var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
var chatSocket = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + '/ws/');
// TODO can DRY some of this setup at least

$('#send-new-message').click(function(e) {
    e.preventDefault();
    try {
        var formArray = $('#new-message-form').serializeArray();
        formArray.push({ 'name': 'recipient', 'value': {{ other_user.id }} });
        var message = JSON.stringify(formArray);
        chatSocket.send(message);
        alert("Message sent!");
        location.reload();
    }
    catch(err) {
        alert("Something went wrong with your connection. Please refresh and try again.");
    }
    return false;
});

</script>
{% endblock %}

message_center/templates/message_center/footer.html
<br/><br/><br/><br/>

message_center/templates/message_center/header.html
<div class="top-bar">
    <div class="top-bar-left msg-ctr-top-left">
        <ul class="menu">
            <li class="menu-text"><a href="{% url 'index' %}">Message Central | {{ user.username }}</a></li>
        </ul>
    </div>
    <div class="top-bar-right mst-ctr-top-right">
        <ul class="menu">
            <li class="menu-text"><a href="{% url 'logout' %}">(logout)</a></li>
        </ul>
    </div>
</div>

message_center/templates/message_center/index.html
{% extends 'message_center/base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
<br/>
<div class="grid-x align-center">
    <div class="callout large primary">
        <div class="row column text-center">
            <h1>Welcome to Message Central, {{ user.username }}!</h1>
            <p class="lead">A non-cleverly-named sample application for the WayUp development team to pore over.</p>
        </div>
    </div>
</div>

<div class="grid-x align-center" id="content">

    <div class="medium-1">
        &nbsp;
    </div>

    <div class="medium-6 cell">
        <p class="instructions">Select a message from your inbox to display the details here. Click the sender's name to view the conversation.<br/></p>
        <div id="selected-message" class="selected-message card">
            <div class="card-divider message-header">
            </div>
            <div class="card-section message-details">
                <h4 class="message-subject"></h4>
                <p class="message-body"></p>
            </div>
        </div>
        <hr/>
        <h3>Or, send a new message:</h3>
        <div id="new-message">
            <form method="post" action="{% url 'index' %}" id="new-message-form">
                {% csrf_token %}
                {{ form }}
                <input id="send-new-message" type="submit" class="button button-small button-primary" value="Send message!">
            </form>
        </div>
    </div>

    <div class="medium-1">
        &nbsp;
    </div>

    <div class="medium-3 cell" data-sticky-container>
        <div class="sticky" data-sticky data-anchor="content" id="inbox">
            <h4>Inbox</h4>
            <ol id="inbox-list">
                {% for message in my_messages %}
                    {% include 'message_center/_sidebar_item.html' with message=message offset=0 %}
                {% endfor %}
            </ol>
            {% if not my_messages %}
                <p id="no-messages">Looks like you don't have any messages. Why don't you send some?</p>
            {% endif %}
            <hr/>
            <h4>Outbox</h4>
            <ol id="outbox-list">
                {% for message in sent_messages %}
                    {% include 'message_center/_sidebar_item.html' with message=message offset=my_messages|length %}
                {% endfor %}
            </ol>
        </div>
    </div>

</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'message_center/reconnecting-websocket.min.js' %}"></script>
<!-- ^ shim for getting around heroku's 60-second request cap -->

<script>
var jsonMessages = {{ json_messages|safe }};
var numNewMsgs = 0;

$('#selected-message').hide();

function updateTitle() {
    if (numNewMsgs === 0) {
        $('title').text('Home');
    } else {
        $('title').text('Home (' + numNewMsgs + ')');
    }
}

function selectMessage(idx) {
    if ($('#' + idx).parent().hasClass('unread-message')) {
        // if it's new
        $('#' + idx).parent().removeClass('unread-message');
        numNewMsgs--;
        updateTitle();
    }    
    $('#selected-message').show();
    var newMsg = jsonMessages[idx];
    if (typeof(newMsg) === "string") {
        newMsg = JSON.parse(newMsg);
    }
    if (newMsg === undefined) {
        return;
    }
    $('#selected-message .message-header').html('<p>From <a href="/conversation/' + newMsg.sender.id + '">' + newMsg.sender.name + "</a> <small>at " + newMsg.created_at + "</small></p>");
    //      ^    `conversation` URL is hard-coded FIXME
    $('#selected-message .message-subject').text(newMsg.subject);
    $('#selected-message .message-body').text(newMsg.body);
    if (newMsg.sender.id === {{ user.id }}) {
        $('#selected-message').attr('class', 'selected-message card by-me');
    } else {
        $('#selected-message').attr('class', 'selected-message card');
    }
}

function makeNewLi(newMsg) {
    newLi = '<li'
    if (newMsg.sender.name !== "{{ user.username }}") {
        newLi += ' class="unread-message"';
    }
    newLi += '><a id="' + thisId + '" onclick="selectMessage(this.id)">"' + newMsg.subject + '" from ' + newMsg.sender.name + '</a></li>';
    // this is the part that drives me craziest TODO FIXME     ^^
    return newLi;
}

function addNewMsg(newMsg) {
    $('#no-messages').hide();
    jsonMessages.push(newMsg);
    if (typeof(newMsg) === "string") {
        newMsg = JSON.parse(newMsg);
    }
    thisId = jsonMessages.length-1
    if (newMsg.sender.name !== "{{ user.username }}") {
        numNewMsgs++;
    }
    newLi = makeNewLi(newMsg);
    $('#inbox-list').prepend(newLi);
    updateTitle();
}

var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
var chatSocket = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + '/ws/');
// TODO use django url?

chatSocket.onmessage = function(e) {
    var data = JSON.parse(e.data);
    var message = data['message'];
    addNewMsg(message);
};

chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
};

$('#send-new-message').click(function(e) {
    e.preventDefault();
    try {
        var message = JSON.stringify($('#new-message-form').serializeArray());
        chatSocket.send(message);
        alert("Message sent!");
        $('#id_subject').val("[no subject]");
        $('#id_body').val("");
    }
    catch(err) {
        alert("Something went wrong with your connection. Please refresh and try again.");
    }
    return false;
});
</script>
{% endblock %}